language: php
# Allows use container-based infrastructure
sudo: false
php:
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_VERSION="4.2.*" DB=mysql
before_script:
  - composer install --no-interaction
  - cp .env.travis .env
script:
  - php bin/phpunit

services:
  - mysql

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test
