<?php

namespace App\Tests\Extra\DataFixture;

use App\Domain\Entity\AbstractEntity;
use App\Domain\Entity\Note;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;

class NoteFixture extends FixtureTemplate
{
    public function load(ObjectManager $manager): void
    {
        parent::load($manager); // TODO: Change the autogenerated stub


        $entity = $this->getEntity();
        $manager->persist($entity);

        $manager->flush();

    }

    public function getEntity() : AbstractEntity
    {
        $note = new Note();
        $note->setTitle('A test title');
        $note->setContent('Some test content');
        $note->setCreationDatetime(new \DateTime());

        $user = $this->getReference("userfixture");

        $note->setUser($user->getId());

        return $note;
    }




}
