<?php

namespace App\Tests\Extra\DataFixture;

use App\Domain\Entity\AbstractEntity;
use App\Domain\Entity\User;
use Doctrine\Common\DataFixtures\ProxyReferenceRepository;
use Doctrine\Common\DataFixtures\ReferenceRepository;
use Doctrine\Common\Persistence\ObjectManager;

class UserFixture extends FixtureTemplate
{

    public function load(ObjectManager $manager): void
    {
        parent::load($manager); // TODO: Change the autogenerated stub

        $entity = $this->getEntity();
        $manager->persist($entity);

        $manager->flush();

        $this->addReference("userfixture", $entity);

    }

    public function getEntity() : AbstractEntity
    {
        $user = new User();
        $user->setEmail('test@eresdev.com');
        $user->setPassword('somePassword1145236@s');
        $user->setActivated(true);
        $user->setDeleted(false);
        $user->setMemberSince(new \DateTime());

        return $user;
    }

}
