noteCreate:
    path: /note
    methods: [ post ]
    controller: App\Controller\CreateNoteController::handleRequest

noteGet:
    path: /note/{noteId}
    methods: [ get ]
    controller: App\Controller\GetNoteController::handleRequest
    requirements:
        noteId: '\d+'

noteDelete:
    path: /note/{noteId}
    methods: [ delete ]
    controller: App\Controller\DeleteNoteController::handleRequest
    requirements:
        noteId: '\d+'

