noteCreate:
    path: /note
    methods: [ post ]
    controller: App\Controller\CreateNoteController::handleRequest

noteGet:
    path: /note/{noteId}
    methods: [ get ]
    controller: App\Controller\RetrieveNoteController::handleRequest
    requirements:
        noteId: '\d+'

noteUpdate:
    path: /note
    methods: [ put ]
    controller: App\Controller\UpdateNoteController::handleRequest

noteDelete:
    path: /note/{noteId}
    methods: [ delete ]
    controller: App\Controller\DeleteNoteController::handleRequest
    requirements:
        noteId: '\d+'

userCreate:
    path: /user
    methods: [ post ]
    controller: App\Controller\CreateUserController::handleRequest
