noteCreate:
    path: /note
    methods: [ post ]
    controller: App\Controller\NoteCreatorController::handleRequest

noteGet:
    path: /note/{noteId}
    methods: [ get ]
    controller: App\Controller\NoteGetterController::handleRequest
    requirements:
        noteId: '\d+'

noteDelete:
    path: /note/{noteId}
    methods: [ delete ]
    controller: App\Controller\NoteDeleterController::handleRequest
    requirements:
        noteId: '\d+'

